# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160607_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='datestr',
            field=models.CharField(default='June 08, 2016', max_length=127),
        ),
        migrations.AddField(
            model_name='comment',
            name='datestr',
            field=models.CharField(default='June 08, 2016', max_length=127),
        ),
    ]
