# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 19:42
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160608_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
