# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160608_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='datestr',
            field=models.CharField(default='June 09, 2016', max_length=127),
        ),
    ]
