# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160609_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Anonymous', max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('datestr', models.CharField(default='June 23, 2016', max_length=127)),
            ],
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='datestr',
            field=models.CharField(default='June 23, 2016', max_length=127),
        ),
    ]
