# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20160623_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.BlogPost'),
            preserve_default=False,
        ),
    ]
