# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_comment_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='datestr',
            field=models.CharField(default='June 23, 2016 - 16:7', max_length=127),
        ),
    ]
