# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20160623_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='datestr',
            field=models.CharField(default='June 23, 2016 - 17:08', max_length=127),
        ),
    ]
