# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20160624_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='datestr',
            field=models.CharField(default='June 24, 2016 2:30 PM PST', max_length=127),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, default='Anonymous', max_length=64, null=True),
        ),
    ]
