# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20160624_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='datestr',
            field=models.CharField(default='June 24, 2016 2:50 PM PST', max_length=127),
        ),
    ]
