# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20160628_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='datestr',
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='datestr',
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(default='Anonymous', max_length=64),
        ),
    ]
