# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20160628_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='url',
            field=models.CharField(default='asdasd', max_length=127),
            preserve_default=False,
        ),
    ]
